name: Terraform Manual Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform Action (plan, apply, destroy)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Terraform Init (must be first Terraform step)
      - name: Terraform Init
        working-directory: vpc
        run: terraform init

      # Terraform Format (check mode)
      - name: Terraform Format
        working-directory: vpc
        run: terraform fmt -check -recursive

      # Terraform Validate (after init)
      - name: Terraform Validate
        working-directory: vpc
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        working-directory: vpc
        run: terraform plan -out=tfplan

      # Terraform Apply (Only if action is apply)
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: vpc
        run: terraform apply -auto-approve tfplan

      # Terraform Destroy (Only if action is destroy)
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: vpc
        run: terraform destroy -auto-approve
